Repository Team-Ampersand/drawWang-Client, pull requests merged in 2024-02, with the labels that each got.

#4 주제 페이지, 명예의전당 페이지 퍼블리싱을 완료하고 라우팅 기능을 추가했어요.
  package-lock.json
  package.json
  src/Assets/svgs/BlueCircle.jsx
  src/Assets/svgs/GrayCircle.jsx
  src/Assets/svgs/Heart.jsx
  src/Assets/svgs/Plus.jsx
  src/Assets/svgs/Report.jsx
  src/Assets/svgs/Search.jsx
  src/Assets/svgs/SwipeLeftArrow.jsx
  src/Assets/svgs/SwipeRightArrow.jsx
  src/Assets/svgs/ThreadBoxArrow.jsx
  src/Assets/svgs/index.jsx
  src/Components/Navbar/index.jsx
  src/Components/Navbar/style.js
  src/Components/Pages/SelectedTopicPage/index.jsx
  src/Components/Pages/SelectedTopicPage/style.js
  src/Components/Pages/TopicPicturePage/index.jsx
  src/Components/Pages/TopicPicturePage/style.js
  src/Components/PopUp/createthread.jsx
  src/Components/PopUp/report.jsx
  src/Components/PopUp/style.js
  src/Components/ThreadBox/createnew.jsx
  src/Components/ThreadBox/halloffame.jsx
  src/Components/ThreadBox/picture.jsx
  src/Components/ThreadBox/style.js
  src/Components/ThreadBox/topic.jsx
  src/Pages/HallOfFamePage/index.jsx
  src/Pages/HallOfFamePage/style.js
  src/Pages/MainPage/index.jsx
  src/Pages/MainPage/style.js
  src/index.jsx
Labels: ⚙ Type: Setting, ✨ Type: Feature, 🎨 Type: Publishing, 🔨 Type: Refector

#5 ✨ :: PaintBoard publishing
  src/Assets/pngs/ToolHide.png
  src/Assets/svgs/Back.jsx
  src/Assets/svgs/ColorPicker.jsx
  src/Assets/svgs/Eraser.jsx
  src/Assets/svgs/Pen.jsx
  src/Assets/svgs/PickToolbar.jsx
  src/Assets/svgs/Redo.jsx
  src/Assets/svgs/ToolBox.jsx
  src/Assets/svgs/index.jsx
  src/Components/Cursor/index.jsx
  src/Components/Cursor/style.js
  src/Components/PaintBoardTools/ColorToolSettings.jsx
  src/Components/PaintBoardTools/EraserToolSettings.jsx
  src/Components/PaintBoardTools/PenToolSettings.jsx
  src/Components/PaintBoardTools/Style.js
  src/Components/PaintBoardTools/index.jsx
  src/Pages/PaintBoard/Style.js
  src/Pages/PaintBoard/index.jsx
  src/index.jsx
Labels: ✨ Type: Feature

#6 Feature/search box
  src/Assets/svgs/ArrowRotation.jsx
  src/Assets/svgs/index.jsx
  src/Components/Navbar/index.jsx
  src/Components/Navbar/style.js
  src/Components/PaintBoardTools/ColorToolSettings.jsx
  src/Components/PaintBoardTools/EraserToolSettings.jsx
  src/Components/PaintBoardTools/PenToolSettings.jsx
  src/Components/PaintBoardTools/index.jsx
  src/Components/Search/Style.js
  src/Components/Search/index.jsx
  src/Pages/PaintBoard/index.jsx
Labels: ✨ Type: Feature, 🎨 Type: Publishing, 🔨 Type: Refector

#7 ✨ :: ThreadPictureNullPage Publishing
  src/Assets/pngs/x.png
  src/Assets/svgs/ChevronLeft.jsx
  src/Assets/svgs/index.jsx
  src/Components/Pages/SelectedTopicPage/index.jsx
  src/Components/Pages/SelectedTopicPage/style.js
  src/Components/ThreadPictureNull/index.jsx
  src/Components/ThreadPictureNull/style.js
  src/Pages/HallOfFamePage/index.jsx
  src/Pages/MainPage/index.jsx
  src/Pages/index.jsx
  src/index.jsx
Labels: 🎨 Type: Publishing
